import { BoxPlan, Translation } from './types';

export const translations: Record<string, Translation> = {
  es: {
    nav: {
      home: 'Inicio',
      shop: 'Tienda',
      about: 'Misión',
      dashboard: 'Mi Cuenta',
      login: 'Entrar',
      logout: 'Salir',
    },
    hero: {
      title: 'El misterio más sostenible',
      subtitle: 'Cajas sorpresa con productos recuperados de Amazon. Calidad verificada, cero desperdicio, y una aventura nueva cada mes.',
      cta: 'Empezar Aventura',
      badge: 'Envío gratis en primer pedido',
    },
    categories: {
      title: '¿Qué puede tocarte?',
      subtitle: 'Aunque el contenido es sorpresa, tú eliges la temática de tu caja.',
      electronics: 'Electrónica',
      electronicsDesc: 'Gadgets, auriculares y accesorios tech verificados.',
      toys: 'Juguetes',
      toysDesc: 'Diversión para todas las edades, desde juegos de mesa hasta figuras.',
      food: 'Alimentación',
      foodDesc: 'Productos gourmet y snacks rescatados de fechas cortas.',
      home: 'Hogar & Mix',
      homeDesc: 'Decoración, cocina y un poco de todo para tu casa.',
    },
    features: {
      sustainable: '100% Circular',
      sustainableDesc: 'Damos una segunda vida a devoluciones de Amazon en perfecto estado.',
      surprise: 'Factor Sorpresa',
      surpriseDesc: 'Nunca sabes qué vendrá, pero siempre supera el valor de tu suscripción.',
      value: 'Ahorro Real',
      valueDesc: 'Productos valorados en hasta un 70% más de lo que pagas.',
    },
    shop: {
      title: 'Configura tu Caja Verde',
      choose: 'Elige tamaño, categoría y modalidad de compra.',
      subscribe: 'Suscríbete y ahorra',
      oneTime: 'Compra única',
      saveText: 'Ahorra 15%',
      addToCart: 'Añadir al carrito',
      selectCategory: 'Elige la temática:',
    },
    dashboard: {
      welcome: 'Hola',
      nextBox: 'Tu próxima caja llega en',
      status: 'Estado',
      playGame: 'Jugar Rasca y Gana',
      scratchTitle: '¡Rasca y Gana!',
      scratchDesc: 'Descubre tu premio de esta semana. Usa el cursor para rascar.',
      won: '¡Felicidades! Has ganado:',
    },
  },
  en: {
    nav: {
      home: 'Home',
      shop: 'Shop',
      about: 'Mission',
      dashboard: 'Dashboard',
      login: 'Login',
      logout: 'Logout',
    },
    hero: {
      title: 'The Sustainable Mystery',
      subtitle: 'Surprise boxes with recovered Amazon products. Verified quality, zero waste, and a new adventure every month.',
      cta: 'Start Adventure',
      badge: 'Free shipping on first order',
    },
    categories: {
      title: 'What\'s inside?',
      subtitle: 'The content is a surprise, but you pick the theme.',
      electronics: 'Electronics',
      electronicsDesc: 'Verified gadgets, headphones, and tech accessories.',
      toys: 'Toys',
      toysDesc: 'Fun for all ages, from board games to action figures.',
      food: 'Food & Pantry',
      foodDesc: 'Gourmet products and snacks rescued from short expiry dates.',
      home: 'Home & Mix',
      homeDesc: 'Decor, kitchenware, and a little bit of everything.',
    },
    features: {
      sustainable: '100% Circular',
      sustainableDesc: 'We give a second life to perfect-condition Amazon returns.',
      surprise: 'Surprise Factor',
      surpriseDesc: 'You never know what you get, but it always exceeds the subscription value.',
      value: 'Real Savings',
      valueDesc: 'Products valued at up to 70% more than what you pay.',
    },
    shop: {
      title: 'Configure your Green Box',
      choose: 'Choose size, category, and purchase mode.',
      subscribe: 'Subscribe & Save',
      oneTime: 'One-time purchase',
      saveText: 'Save 15%',
      addToCart: 'Add to Cart',
      selectCategory: 'Select Theme:',
    },
    dashboard: {
      welcome: 'Hello',
      nextBox: 'Your next box arrives in',
      status: 'Status',
      playGame: 'Play Scratch & Win',
      scratchTitle: 'Scratch & Win!',
      scratchDesc: 'Reveal your weekly prize. Use your cursor to scratch.',
      won: 'Congrats! You won:',
    },
  },
};

export const BOX_PLANS: BoxPlan[] = [
  {
    id: 'box_s',
    name: 'Caja Pequeña',
    priceOneTime: 18,
    priceSubscription: 15,
    size: 'small',
    description: 'Perfecta para un detalle. Contiene 2-3 artículos.',
    features: ['Valor asegurado: >25€', '2-3 Productos', 'Zero Waste'],
    image: 'https://picsum.photos/400/400?random=1',
  },
  {
    id: 'box_m',
    name: 'Caja Mediana',
    priceOneTime: 30,
    priceSubscription: 25,
    size: 'medium',
    description: 'La más popular. Equilibrio ideal de sorpresas.',
    features: ['Valor asegurado: >45€', '3-5 Productos', 'Envío Prioritario'],
    image: 'https://picsum.photos/400/400?random=2',
  },
  {
    id: 'box_l',
    name: 'Caja Grande',
    priceOneTime: 50,
    priceSubscription: 40,
    size: 'large',
    description: 'Experiencia completa con productos premium.',
    features: ['Valor asegurado: >80€', '5-7 Productos', 'Regalo extra'],
    image: 'https://picsum.photos/400/400?random=3',
  },
];